### ISSUE TITLE
[Feature 5.2]  create staff schedule

### ISSUE THREAD

**Issue by zoeyzlee** [CSC207-2023Y-UofT/Transit-Simulator#33]
- each staff needs a schedule (from plot)
- done by checking what line they're working on that day
- line assigned to train engineers/operators by admins
- AddToLine interface has methods addEmployeeToLine and checkLine, and admin implements that interface so they can do both administrative things. employees call on the public methods written in admin to check what line they're on

**Comment by gracelliu** [comment]
done in management page
